# ansible-galaxy install -r roles/requirements.yml
---
- src: git@gitlab.cloud.switch.ch:petasolutions-switch-ch/ansible-role-users.git
  scm: git
  version: master
  name: users

- src: git@gitlab-int.switch.ch:toolbox2/jitsi-deploy-vars.git
  scm: git
  version: master
  name: jitsi-deploy-vars

