---
# Copy the original files. (accordingly force:no)
- name: Backup old jitsi-meet.
  copy:
    src: /usr/share/jitsi-meet
    dest: "/usr/share/jitsi-meet-bkp-original"
    force: no
    remote_src: yes
  tags:
    jitsi

- name: Remove backuped jitsi-meet.
  file:
    path: /usr/share/jitsi-meet
    state: absent
  tags: jitsi

- name: Copy SWITCH jitsi-meet build
  unarchive:
    src: jitsi-meet.tar.bz2
    dest: /usr/share/
    owner: root
    group: root
    creates: /usr/share/jitsi-meet
  tags:
    jitsi

- name: Add welcomePage dynamic customization.
  blockinfile:
    path: /usr/share/jitsi-meet/static/welcomePageAdditionalContent.html
    block: |2
          <!-- Matomo -->
          <script>
            var _paq = _paq || [];
            _paq.push(["setDocumentTitle", document.domain + "/" + document.title]);
            _paq.push(["setCookieDomain", "{{matomo_cookie_domain}}"]);
            _paq.push(['trackPageView']);
            _paq.push(['enableLinkTracking']);
            (function() {
              var u="//{{matomo_server}}";
              _paq.push(['setTrackerUrl', u+'piwik.php']);
              _paq.push(['setSiteId', '{{matomo_site_id}}']);
              var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
              g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
            })();
          </script>
          <!-- End Matomo Code -->
    insertbefore: '^</template>'
  when: matomo_enabled

- name: jitsi | jitsi-meet config.js
  become: yes
  tags:
    - conf
    - webconf
  template:
    src: jitsi-config.j2
    dest: /etc/jitsi/meet/{{ jitsi_fqdn }}-config.js
    mode: 0644

- name: jitsi | overwrite nginx config file
  become: yes
  tags:
    - jitsi
    - conf
  template:
    src: nginx-jitsi.conf.j2
    dest: /etc/nginx/sites-available/{{ jitsi_fqdn }}.conf
    mode: 0644
  notify: restart nginx

- name: jitsi | enable site
  file:
    src: /etc/nginx/sites-available/{{ jitsi_fqdn }}.conf
    dest: /etc/nginx/sites-enabled/{{ jitsi_fqdn }}.conf
    state: link
  tags:
    - jitsi
    - conf
