---
- name: Create and launch mailbox VM
  hosts: localhost
  vars:
    stream_servicename: "jibri"
    stream_vm_image: "Ubuntu Bionic 18.04 (SWITCHengines)"
    stream_vm_flavor: "m1.medium"
    stream_vm_ssh_key: "bisig-rsa"
    stream_vm_storage_type: "ceph-standard"
    stream_vm_storage_size: 30
    stream_vm_network: "private"
    stream_vm_auto_ip: 'no'
    stream_secgroups: 
      - SSH
  tasks:
  - name: Create security groups
    os_security_group:
      state: present
      name: "{{ item }}"
    loop: "{{ stream_secgroups }}"
  - name: Add ssh rule (IPv6)
    os_security_group_rule:
      security_group: "SSH"
      protocol: tcp
      port_range_min: 22
      port_range_max: 22
      ethertype: IPv6
      remote_ip_prefix: ::/0
  - name: Add ssh rule (IPv4)
    os_security_group_rule:
      security_group: "SSH"
      protocol: tcp
      port_range_min: 22
      port_range_max: 22
      ethertype: IPv4
      remote_ip_prefix: 0.0.0.0/0
  
  - include: start_stream.yml
    loop: "{{ groups[stream_servicename] }}"
