---
###
# Please check the vars
###

- name: Create and launch videobridge VM
  hosts: localhost
  vars:
    jitsi_vb_vm_flavor: "c1.xlarge" # 8 VCPU / 8GB RAM
    jitsi_vb_ssh_key: "valery-rsa"
    jitsi_vb_vm_network: "switch-net"
    jitsi_vb_vm_image: "Ubuntu Bionic 18.04 (SWITCHengines)"
    jitsi_vb_volume_type: "ceph-standard"
    jitsi_vb_volume_size: "20"
  tasks:
  - name: Create security groups - SSH, jitsi-videobridge
    os_security_group:
      state: present
      name: "{{ item }}"
    loop:
        - SSH
        - jitsi-videobridge
  - name: Add ssh rule (IPv6)
    os_security_group_rule:
      security_group: SSH
      protocol: tcp
      port_range_min: 22
      port_range_max: 22
      ethertype: IPv6
      remote_ip_prefix: ::/0
  - name: Add ssh rule (IPv4)
    os_security_group_rule:
      security_group: SSH
      protocol: tcp
      port_range_min: 22
      port_range_max: 22
      ethertype: IPv4
      remote_ip_prefix: 0.0.0.0/0
  - name: Add security group rule - port 10000 (IPv4)
    os_security_group_rule:
      security_group: jitsi-videobridge
      protocol: tcp
      port_range_min: 10000
      port_range_max: 10000
      ethertype: IPv4
      remote_ip_prefix: 0.0.0.0/0
  - name: Add security group rule - port 10000 (IPv6)
    os_security_group_rule:
      security_group: jitsi-videobridge
      protocol: tcp
      port_range_min: 10000
      port_range_max: 10000
      ethertype: IPv6
      remote_ip_prefix: ::/0
  - name: Add security group rule - port 10000 udp (IPv4)
    os_security_group_rule:
      security_group: jitsi-videobridge
      protocol: udp
      port_range_min: 10000
      port_range_max: 10000
      ethertype: IPv4
      remote_ip_prefix: 0.0.0.0/0
  - name: Add security group rule - port 10000 udp (IPv6)
    os_security_group_rule:
      security_group: jitsi-videobridge
      protocol: udp
      port_range_min: 10000
      port_range_max: 10000
      ethertype: IPv6
      remote_ip_prefix: ::/0
  - name: Add security group rule - port 5347 (IPv4)
    os_security_group_rule:
      security_group: jitsi-videobridge
      protocol: tcp
      port_range_min: 5347
      port_range_max: 5347
      ethertype: IPv4
      remote_ip_prefix: 0.0.0.0/0
  - name: Add security group rule - port 5347 (IPv6)
    os_security_group_rule:
      security_group: jitsi-videobridge
      protocol: tcp
      port_range_min: 5347
      port_range_max: 5347
      ethertype: IPv6
      remote_ip_prefix: ::/0
  - name: Add security group rule - port 5222 (IPv4)
    os_security_group_rule:
      security_group: jitsi-videobridge
      protocol: tcp
      port_range_min: 5222
      port_range_max: 5222
      ethertype: IPv4
      remote_ip_prefix: 0.0.0.0/0
  - name: Add security group rule - port 5222 (IPv6)
    os_security_group_rule:
      security_group: jitsi-videobridge
      protocol: tcp
      port_range_min: 5222
      port_range_max: 5222
      ethertype: IPv6
      remote_ip_prefix: ::/0

  - name: Create all Videobridges
    include_tasks: start_videobridges.yml
    loop: "{{ groups['videobridge'] }}"
