# Jitsi  deployment and configuration
#
#     ansible-galaxy install -fr roles/requirements.yml
#
---
- name: configure server
  hosts: jitsi
  become: yes
  vars:
    videobridge_only: false
  roles:
    - users
    - nginx
    - shib
    - role: jitsi
      tags: jitsi
    - site24x7

- name: videobridge
  hosts: videobridge
  become: yes
  vars:
    videobridge_only: true
  roles:
    - users
    - role: jitsi
      tags: jitsi
    - site24x7

- name: setup view
  hosts: view
  become: yes
  roles:
    - users
    - site24x7
    - nginx
    - view

- name: Configure Jibris
  hosts: jibri
  become: yes
  roles:
    - role: users
      when: not ansible_check_mode
    - role: jibri
      tags: jibri

- name: Configure Coturn
  hosts: coturn
  become: yes
  vars:
    certbot_admin_email: maps@switch.ch
    certbot_create_if_missing: true
    certbot_create_standalone_stop_services: []
    certbot_certs:
      - domains:
          - test-jitsi-coturn-1001.meet.switch.ch
  roles:
    - role: users
      when: not ansible_check_mode
    - role: certbot
      tags: coturn
    - role: coturn
      tags: coturn
