---
- debug: msg="Create {{ item.split('.')[0] }}"

- name: Create root volume
  os_volume:
      display_name: "{{ item.split('.')[0] | lower }}-root"
      image: "{{ jitsi_vb_vm_image }}"
      volume_type: "ceph-standard"
      size: "20"

- name: "Launch Videobridge VM and generate IPv4"
  os_server:
      auto_ip: yes
      boot_volume: "{{ item.split('.')[0] | lower }}-root"
      flavor: "{{ jitsi_vb_vm_flavor }}"
      key_name: "{{ jitsi_vb_ssh_key }}"
      name: "{{ item.split('.')[0] | lower }}"
      state: present
      nics:
      - net-name: "{{ jitsi_vb_vm_network }}"
      security_groups:
      - "SSH"
      - "jitsi"
      wait: yes
  register: vb
  when: not ansible_check_mode

- debug:
    msg:
      - "Server private IPv4: {{ vb.openstack.private_v4 }}"
      - "Server IPv4: {{ vb.openstack.public_v4 }}"
      - "Server IPv6: {{ vb.openstack.public_v6 }} "
      - "Insert the values into ./host_vars/HOSTNAME/vars.yml and vault.yml. Add callstats.io and ssl certs."
      - "Videobridge IPv4: {{ vb.openstack.public_v4 }}"
      - "Add hosts to ./inventory/UNINAME"
      - "Call: ansible-playbook -i inventory/UNINAME main.yml "
  when: not ansible_check_mode
