---
- debug: msg="Create {{ item.split('.')[0] }}"

- name: Create root volume
  os_volume:
      display_name: "{{ item.split('.')[0] | lower }}-root"
      image: "{{ stream_vm_image }}"
      volume_type: "{{ stream_vm_storage_type }}"
      size: "{{stream_vm_storage_size}}"

- name: "Launch Videobridge VM and generate IPv4"
  os_server:
      auto_ip: "{{ stream_vm_auto_ip | default('yes') }}"
      boot_volume: "{{ item.split('.')[0] | lower }}-root"
      flavor: "{{ stream_vm_flavor }}"
      key_name: "{{ stream_vm_ssh_key }}"
      name: "{{ item.split('.')[0] | lower }}"
      state: present
      nics:
      - net-name: "{{ stream_vm_network }}"
      security_groups: "{{ stream_secgroups }}"
      wait: yes
  register: os
  when: not ansible_check_mode

- debug:
    msg:
      - "Server private IPv4: {{ os.openstack.private_v4 }}"
      - "Server IPv4: {{ os.openstack.public_v4 }}"
      - "Server IPv6: {{ os.openstack.public_v6 }} "
      - "Call: ansible-playbook -i inventory/production main.yml --limit {{ stream_servicename }} -D"
  when: not ansible_check_mode
